server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/habitplay
    username: habitPlayAdmin
    password: habitPlayAdmin.
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    fail-on-unsupported-database: false
    ignoreUnknownMigrations: true
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

security:
  jwt:
    secret: supersecretkeywithmorethan32characters123!@#
    expiration: 86400000

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html